FROM hyperledger/fabric-peer
# y12docker/dltdojo-fabgopeer
ADD examples /opt/gopath/src/github.com/hyperledger/fabric/examples/
# RUN ls -al /opt/gopath/src/github.com/hyperledger/fabric/examples/
