DCNAME=devethgo
DNAME=y12docker/dltdojo-ethparity:1.5.0
DCNAME=devparity
alias build='docker build -t ${DNAME} . ; echo "docker build -t ${DNAME}"'
alias dparity='docker run -t ${DNAME} parity'
alias poadc='docker-compose -p $DCNAME -f buildpoa.yml'
alias poadcend='poadc stop ; poadc rm -f'
alias poadcup='poadcend ; poadc up -d'
alias poa0='docker exec -it ${DCNAME}_poa0_1'
alias poa1='docker exec -it ${DCNAME}_poa1_1'
alias dc='docker-compose -p $DCNAME -f poa.yml'
alias dcend='dc stop ; dc rm -f'
alias dcup='dcend ; dc up -d'
