DNAME=y12docker/dltdojo-ccoin
alias build='docker build -t ${DNAME} . ; echo "docker build -t ${DNAME}";  docker images | grep ${DNAME}'
alias drun='docker run -it ${DNAME}'
PNAME=ccoin
DCNAME=dev${PNAME}
alias dc='docker-compose -p $DCNAME -f peers.yml'
alias dcend='dc stop ; dc rm -f'
alias dcup='dcend ; dc up -d; dc ps'
alias dexec1='docker exec -it ${DCNAME}_${PNAME}1_1'
alias cli1='dexec1 omnicore-cli'
