version: '2'
services:
  node0:
    image: dltdojo/clique:1.6.6
    volumes:
      - dltdojo:/dltdojo
    command: "./start.sh"
  node1:
    image: dltdojo/clique:1.6.6
    volumes:
      - dltdojo:/dltdojo
    command: "./start.sh"
  node2:
    image: dltdojo/clique:1.6.6
    volumes:
      - dltdojo:/dltdojo
    command: "./start.sh"
volumes:
  dltdojo:
    external: true