DCN=levelx
alias dc='docker-compose -p levelx -f levelx-peers.yml'
alias dcup='dc stop && dc rm && dc up -d'
alias vp0='docker exec -i -t levelx_vp0_1'
alias vp0cli='vp0 bitcoin-cli -conf=/opt/btc/bitcoin.conf -regtest -rpcport=18332'
alias vp1='docker exec -i -t levelx_vp1_1'
alias vp1cli='vp1 bitcoin-cli -conf=/opt/btc/bitcoin.conf -regtest -rpcport=18332'
alias vp2='docker exec -i -t levelx_vp2_1'
alias vp2cli='vp2 bitcoin-cli -conf=/opt/btc/bitcoin.conf -regtest -rpcport=18332'
alias vp3='docker exec -i -t levelx_vp3_1'
alias vp3cli='vp3 bitcoin-cli -conf=/opt/btc/bitcoin.conf -regtest -rpcport=18332'
alias vp4='docker exec -i -t levelx_vp4_1'
alias vp4cli='vp4 bitcoin-cli -conf=/opt/btc/bitcoin.conf -regtest -rpcport=18332'
alias vp5='docker exec -i -t levelx_vp5_1'
alias vp5cli='vp5 bitcoin-cli -conf=/opt/btc/bitcoin.conf -regtest -rpcport=18332'
alias vp6='docker exec -i -t levelx_vp6_1'
alias vp6cli='vp6 bitcoin-cli -conf=/opt/btc/bitcoin.conf -regtest -rpcport=18332'