version: '2'
services:
  btcboot:
    image: y12docker/dltdojo-bitcoin
    command: '/start.sh'
    ports:
        - "18332:18332"
  bcc:
    image: y12docker/dltdojo-bitcoin
    command: '/start.sh'
  bcu:
    image: y12docker/dltdojo-btcunlimited
    command: '/start.sh'
  abe:
    image: y12docker/dltdojo-abe
    command: '/start.sh'
    ports:
        - "12750:12750"
