version: '2'
services:
  httpd:
    build: ./httpd
    ports:
      - "8080:80"
  backend:
    build: ./backend
    ports:
      - "8081:80"
  fullstack:
    build: ./fullstack
    ports:
      - "8082:3000"
  db:
    image: mariadb:10.1
    environment:
      - MYSQL_ROOT_PASSWORD=root
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_HOST=db
    ports:
        - "8088:80"
