FROM y12docker/kotlin-gradle:3.3
RUN apk add --no-cache git bash curl
RUN git clone --depth=1 https://github.com/corda/corda /corda
RUN cd /corda ; ./gradlew wrapper --gradle-version 2.10
RUN cd /corda ; ./gradlew build --info
WORKDIR /corda
