[parity]
chain = "darkorange.json"
[network]
port = 30303
[rpc]
interface = "0.0.0.0"
port = 8545
cors = "*"
hosts = ["all"]
apis = ["web3", "eth", "net", "personal", "parity", "parity_set", "traces", "rpc", "parity_accounts"]
# [ui]
# port = 8180
# [dapps]
# port = 8080
[account]
#password = ["node.pwds"]
[mining]
#engine_signer = "0x0000000000000000000000000000000000000092"
reseal_on_txs = "none"
